import type { Album } from "@/lib/types";

/**
 * Typed album data — the source of truth for the gallery. Originally migrated
 * from Cloudinary (publicIds verified live at migration time); now maintained
 * by hand here. Add or edit albums directly in this file.
 *
 * TODO (owner): alt texts are city-level defaults — refine per photo when
 * you can (better for accessibility and Google Images).
 */
export const albums: Album[] = [
  {
    slug: "amsterdam",
    title: "Amsterdam",
    country: "Netherlands",
    description: "Canals, bicycles, and brick. Amsterdam between morning and golden hour.",
    cover: { publicId: "Europe/Netherlands/Amsterdam/DSCF5151_eintko", alt: "Travel photograph from Amsterdam, Netherlands", city: "Amsterdam" },
    photos: [
      { publicId: "Europe/Netherlands/Amsterdam/DSCF5151_eintko", alt: "Travel photograph from Amsterdam, Netherlands", city: "Amsterdam" },
      { publicId: "Europe/Netherlands/Amsterdam/DSCF5199_mnuy5h", alt: "Travel photograph from Amsterdam, Netherlands", city: "Amsterdam" },
      { publicId: "Europe/Netherlands/Amsterdam/DSCF5215_xjesqe", alt: "Travel photograph from Amsterdam, Netherlands", city: "Amsterdam" },
      { publicId: "Europe/Netherlands/Amsterdam/DSCF5238_czeja8", alt: "Travel photograph from Amsterdam, Netherlands", city: "Amsterdam" },
      { publicId: "Europe/Netherlands/Amsterdam/DSCF5239_ghiibd", alt: "Travel photograph from Amsterdam, Netherlands", city: "Amsterdam" },
      { publicId: "Europe/Netherlands/Amsterdam/DSCF5265_dcj5fj", alt: "Travel photograph from Amsterdam, Netherlands", city: "Amsterdam" },
      { publicId: "Europe/Netherlands/Amsterdam/_DSF4918_edr9qv", alt: "Travel photograph from Amsterdam, Netherlands", city: "Amsterdam" },
      { publicId: "Europe/Netherlands/Amsterdam/_DSF5525_stulx2", alt: "Travel photograph from Amsterdam, Netherlands", city: "Amsterdam" },
      { publicId: "Europe/Netherlands/Amsterdam/_DSF5558_ft58hq", alt: "Travel photograph from Amsterdam, Netherlands", city: "Amsterdam" },
    ],
  },
  {
    slug: "london",
    title: "London",
    country: "United Kingdom",
    description: "Grey light and good contrast. London street photography on Fujifilm.",
    cover: { publicId: "Europe/England/London/DSCF4067_u2jdmv", alt: "Travel photograph from London, United Kingdom", city: "London" },
    photos: [
      { publicId: "Europe/England/London/DSCF2923_ldbbel", alt: "Travel photograph from London, United Kingdom", city: "London" },
      { publicId: "Europe/England/London/DSCF3157_yn4dkm", alt: "Travel photograph from London, United Kingdom", city: "London" },
      { publicId: "Europe/England/London/DSCF3380_vloirh", alt: "Travel photograph from London, United Kingdom", city: "London" },
      { publicId: "Europe/England/London/DSCF3429_g2hapk", alt: "Travel photograph from London, United Kingdom", city: "London" },
      { publicId: "Europe/England/London/DSCF4067_u2jdmv", alt: "Travel photograph from London, United Kingdom", city: "London" },
      { publicId: "Europe/England/London/_DSF3537_ptqocy", alt: "Travel photograph from London, United Kingdom", city: "London" },
      { publicId: "Europe/England/London/_DSF3606_smxjbu", alt: "Travel photograph from London, United Kingdom", city: "London" },
      { publicId: "Europe/England/London/_DSF3651_uqlzgg", alt: "Travel photograph from London, United Kingdom", city: "London" },
      { publicId: "Europe/England/London/_DSF3664_cjq3ne", alt: "Travel photograph from London, United Kingdom", city: "London" },
      { publicId: "Europe/England/London/_DSF3689_bmohfd", alt: "Travel photograph from London, United Kingdom", city: "London" },
      { publicId: "Europe/England/London/_DSF3690_jehqle", alt: "Travel photograph from London, United Kingdom", city: "London" },
      { publicId: "Europe/England/London/_DSF3714_qx6eei", alt: "Travel photograph from London, United Kingdom", city: "London" },
      { publicId: "Europe/England/London/_DSF3740_i6y5e7", alt: "Travel photograph from London, United Kingdom", city: "London" },
      { publicId: "Europe/England/London/_DSF3753_o0ws96", alt: "Travel photograph from London, United Kingdom", city: "London" },
      { publicId: "Europe/England/London/_DSF3758_fdtmxd", alt: "Travel photograph from London, United Kingdom", city: "London" },
      { publicId: "Europe/England/London/_DSF3827_rbazjt", alt: "Travel photograph from London, United Kingdom", city: "London" },
      { publicId: "Europe/England/London/_DSF3829_oewssd", alt: "Travel photograph from London, United Kingdom", city: "London" },
      { publicId: "Europe/England/London/_DSF3914_vicyzk", alt: "Travel photograph from London, United Kingdom", city: "London" },
      { publicId: "Europe/England/London/_DSF3923_j9swyz", alt: "Travel photograph from London, United Kingdom", city: "London" },
      { publicId: "Europe/England/London/_DSF3934_pvxnk3", alt: "Travel photograph from London, United Kingdom", city: "London" },
      { publicId: "Europe/England/London/_DSF3958_ntares", alt: "Travel photograph from London, United Kingdom", city: "London" },
      { publicId: "Europe/England/London/_DSF3975_oqi79t", alt: "Travel photograph from London, United Kingdom", city: "London" },
      { publicId: "Europe/England/London/_DSF3989_gojnnm", alt: "Travel photograph from London, United Kingdom", city: "London" },
      { publicId: "Europe/England/London/_DSF3997_me3tap", alt: "Travel photograph from London, United Kingdom", city: "London" },
      { publicId: "Europe/England/London/_DSF4003_falv5q", alt: "Travel photograph from London, United Kingdom", city: "London" },
      { publicId: "Europe/England/London/_DSF4125_lrwdvo", alt: "Travel photograph from London, United Kingdom", city: "London" },
      { publicId: "Europe/England/London/_DSF4170_wbirug", alt: "Travel photograph from London, United Kingdom", city: "London" },
      { publicId: "Europe/England/London/_DSF4206_eokndq", alt: "Travel photograph from London, United Kingdom", city: "London" },
      { publicId: "Europe/England/London/_DSF4298_ifiljc", alt: "Travel photograph from London, United Kingdom", city: "London" },
      { publicId: "Europe/England/London/_DSF4312_mdydsu", alt: "Travel photograph from London, United Kingdom", city: "London" },
    ],
  },
  {
    slug: "rome",
    title: "Rome",
    country: "Italy",
    description: "Two and a half thousand years of backdrop. Rome in passing light.",
    cover: { publicId: "Europe/Italy/Rome/_DSF8677_f4kask", alt: "Travel photograph from Rome, Italy", city: "Rome" },
    photos: [
      { publicId: "Europe/Italy/Rome/_DSF8677_f4kask", alt: "Travel photograph from Rome, Italy", city: "Rome" },
      { publicId: "Europe/Italy/Rome/_DSF8692_iomncd", alt: "Travel photograph from Rome, Italy", city: "Rome" },
      { publicId: "Europe/Italy/Rome/_DSF9029_faupm4", alt: "Travel photograph from Rome, Italy", city: "Rome" },
      { publicId: "Europe/Italy/Rome/_DSF9035_hlxndt", alt: "Travel photograph from Rome, Italy", city: "Rome" },
      { publicId: "Europe/Italy/Rome/_DSF9145_wzbkei", alt: "Travel photograph from Rome, Italy", city: "Rome" },
      { publicId: "Europe/Italy/Rome/_DSF9165_m9lju8", alt: "Travel photograph from Rome, Italy", city: "Rome" },
      { publicId: "Europe/Italy/Rome/_DSF9168_tct8a9", alt: "Travel photograph from Rome, Italy", city: "Rome" },
      { publicId: "Europe/Italy/Rome/_DSF9317_puj4e8", alt: "Travel photograph from Rome, Italy", city: "Rome" },
      { publicId: "Europe/Italy/Rome/_DSF9318_f44n2e", alt: "Travel photograph from Rome, Italy", city: "Rome" },
    ],
  },
  {
    slug: "como",
    title: "Como",
    country: "Italy",
    description: "The lake, the mountains, and the slow boats between them.",
    cover: { publicId: "Europe/Italy/Como/_DSF8423_asmsav", alt: "Travel photograph from Como, Italy", city: "Como" },
    photos: [
      { publicId: "Europe/Italy/Como/_DSF8423_asmsav", alt: "Travel photograph from Como, Italy", city: "Como" },
      { publicId: "Europe/Italy/Como/_DSF8467_tpqthh", alt: "Travel photograph from Como, Italy", city: "Como" },
      { publicId: "Europe/Italy/Como/_DSF8539_zhsttg", alt: "Travel photograph from Como, Italy", city: "Como" },
      { publicId: "Europe/Italy/Como/_DSF8829_vaaddu", alt: "Travel photograph from Como, Italy", city: "Como" },
      { publicId: "Europe/Italy/Como/_DSF8837_fxgpjg", alt: "Travel photograph from Como, Italy", city: "Como" },
      { publicId: "Europe/Italy/Como/_DSF8848_vtmjxj", alt: "Travel photograph from Como, Italy", city: "Como" },
      { publicId: "Europe/Italy/Como/_DSF8889_iqzqon", alt: "Travel photograph from Como, Italy", city: "Como" },
      { publicId: "Europe/Italy/Como/_DSF8894_wnggrm", alt: "Travel photograph from Como, Italy", city: "Como" },
    ],
  },
  {
    slug: "paraty",
    title: "Paraty",
    country: "Brazil",
    description: "Whitewashed walls and cobblestones on Brazil's green coast.",
    cover: { publicId: "South America/Brasil/Paraty/_DSF6142_kyrmhf", alt: "Travel photograph from Paraty, Brazil", city: "Paraty" },
    photos: [
      { publicId: "South America/Brasil/Paraty/_DSF6142_kyrmhf", alt: "Travel photograph from Paraty, Brazil", city: "Paraty" },
      { publicId: "South America/Brasil/Paraty/_DSF6218_u36sym", alt: "Travel photograph from Paraty, Brazil", city: "Paraty" },
      { publicId: "South America/Brasil/Paraty/_DSF6430_tvea5z", alt: "Travel photograph from Paraty, Brazil", city: "Paraty" },
      { publicId: "South America/Brasil/Paraty/_DSF6599_nfycnx", alt: "Travel photograph from Paraty, Brazil", city: "Paraty" },
      { publicId: "South America/Brasil/Paraty/_DSF6690_m9f9bt", alt: "Travel photograph from Paraty, Brazil", city: "Paraty" },
      { publicId: "South America/Brasil/Paraty/_DSF6700_cxncpv", alt: "Travel photograph from Paraty, Brazil", city: "Paraty" },
      { publicId: "South America/Brasil/Paraty/_DSF6714_qluuhj", alt: "Travel photograph from Paraty, Brazil", city: "Paraty" },
      { publicId: "South America/Brasil/Paraty/_DSF6758_schmbi", alt: "Travel photograph from Paraty, Brazil", city: "Paraty" },
      { publicId: "South America/Brasil/Paraty/_DSF6816_oo99ua", alt: "Travel photograph from Paraty, Brazil", city: "Paraty" },
      { publicId: "South America/Brasil/Paraty/_DSF6822_picena", alt: "Travel photograph from Paraty, Brazil", city: "Paraty" },
      { publicId: "South America/Brasil/Paraty/_DSF6898_khrsl8", alt: "Travel photograph from Paraty, Brazil", city: "Paraty" },
      { publicId: "South America/Brasil/Paraty/_DSF6914_vg7ads", alt: "Travel photograph from Paraty, Brazil", city: "Paraty" },
      { publicId: "South America/Brasil/Paraty/_DSF6939_hvcnnm", alt: "Travel photograph from Paraty, Brazil", city: "Paraty" },
      { publicId: "South America/Brasil/Paraty/_DSF6972_g2l872", alt: "Travel photograph from Paraty, Brazil", city: "Paraty" },
      { publicId: "South America/Brasil/Paraty/_DSF7007_m4cvus", alt: "Travel photograph from Paraty, Brazil", city: "Paraty" },
      { publicId: "South America/Brasil/Paraty/_DSF7012_sixbaz", alt: "Travel photograph from Paraty, Brazil", city: "Paraty" },
      { publicId: "South America/Brasil/Paraty/_DSF7015_ticqvt", alt: "Travel photograph from Paraty, Brazil", city: "Paraty" },
      { publicId: "South America/Brasil/Paraty/_DSF7191_ew93do", alt: "Travel photograph from Paraty, Brazil", city: "Paraty" },
      { publicId: "South America/Brasil/Paraty/_DSF7241_wfx39b", alt: "Travel photograph from Paraty, Brazil", city: "Paraty" },
      { publicId: "South America/Brasil/Paraty/_DSF7247_qgj2ds", alt: "Travel photograph from Paraty, Brazil", city: "Paraty" },
      { publicId: "South America/Brasil/Paraty/_DSF7257_m6ufsg", alt: "Travel photograph from Paraty, Brazil", city: "Paraty" },
      { publicId: "South America/Brasil/Paraty/_DSF7286_xz6zgy", alt: "Travel photograph from Paraty, Brazil", city: "Paraty" },
      { publicId: "South America/Brasil/Paraty/_DSF7290_ywpl7e", alt: "Travel photograph from Paraty, Brazil", city: "Paraty" },
      { publicId: "South America/Brasil/Paraty/_DSF7300_qkkqhi", alt: "Travel photograph from Paraty, Brazil", city: "Paraty" },
      { publicId: "South America/Brasil/Paraty/_DSF7304_ititwe", alt: "Travel photograph from Paraty, Brazil", city: "Paraty" },
      { publicId: "South America/Brasil/Paraty/_DSF7369_ripd3f", alt: "Travel photograph from Paraty, Brazil", city: "Paraty" },
      { publicId: "South America/Brasil/Paraty/_DSF7381_sh53dn", alt: "Travel photograph from Paraty, Brazil", city: "Paraty" },
      { publicId: "South America/Brasil/Paraty/_DSF7394_mxxz3l", alt: "Travel photograph from Paraty, Brazil", city: "Paraty" },
      { publicId: "South America/Brasil/Paraty/_DSF7417_rodbqz", alt: "Travel photograph from Paraty, Brazil", city: "Paraty" },
      { publicId: "South America/Brasil/Paraty/_DSF7427_lbb3jm", alt: "Travel photograph from Paraty, Brazil", city: "Paraty" },
      { publicId: "South America/Brasil/Paraty/_DSF7469_tjtspy", alt: "Travel photograph from Paraty, Brazil", city: "Paraty" },
    ],
  },
  {
    slug: "cartagena",
    title: "Cartagena",
    country: "Colombia",
    description: "Color on every wall. Cartagena's old town in Caribbean light.",
    cover: { publicId: "South America/Colombia/Cartagena/_X100371_yuewy8", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
    photos: [
      { publicId: "South America/Colombia/Cartagena/_X100371_yuewy8", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_X100400_decasz", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_X100414_dx7tpk", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_X100418_y5zuyl", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_X100424_sal74s", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_X100426_sibsb5", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_X100433_sehtaz", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_XPR0737_pmphcg", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_XPR0744_jacljf", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_XPR0753_fqwfht", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_XPR0755_uufig7", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_XPR0757_bupddt", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_XPR0758_uq29mq", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_XPR0760_fxosz9", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_XPR0764_nspbxe", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_XPR0772_oj0nex", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_XPR0775_p6mc4i", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_XPR0797_w7kqki", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_XPR0845_fk2gvl", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_XPR0853_unfd0t", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_XPR0861_c6qgcg", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_XPR0862_fctbmy", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_XPR0887_dqxuaq", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_XPR0890_kmanle", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_XPR0911_pfv5wz", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_XPR0951_bcuhhq", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_XPR0962_huzm6e", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_XPR0964_zr0saw", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_XPR0965_rwfsvw", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_XPR0972_qze42t", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_XPR0984_cztr89", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_XPR0987_zodyzp", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_XPR0992_mba0k3", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_XPR1008_kcwvou", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_XPR1017_ybz2ss", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_XPR1023_lrq3zw", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_XPR1026_zuru7s", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_XPR1053_o01ceo", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
      { publicId: "South America/Colombia/Cartagena/_XPR1060_ponjeh", alt: "Travel photograph from Cartagena, Colombia", city: "Cartagena" },
    ],
  },
  {
    slug: "positano",
    title: "Positano",
    country: "Italy",
    description: "The town that climbs out of the sea, one pastel floor at a time.",
    cover: { publicId: "Europe/Italy/Positano/_DSF9449_hvgxe6", alt: "Travel photograph from Positano, Italy", city: "Positano" },
    photos: [
      { publicId: "Europe/Italy/Positano/_DSF9277_gxzwm4", alt: "Travel photograph from Positano, Italy", city: "Positano" },
      { publicId: "Europe/Italy/Positano/_DSF9420_dvkjm7", alt: "Travel photograph from Positano, Italy", city: "Positano" },
      { publicId: "Europe/Italy/Positano/_DSF9443_e5vhpk", alt: "Travel photograph from Positano, Italy", city: "Positano" },
      { publicId: "Europe/Italy/Positano/_DSF9449_hvgxe6", alt: "Travel photograph from Positano, Italy", city: "Positano" },
      { publicId: "Europe/Italy/Positano/_DSF9486_oiofl2", alt: "Travel photograph from Positano, Italy", city: "Positano" },
    ],
  },
  {
    slug: "amalfi",
    title: "Amalfi",
    country: "Italy",
    description: "Lemon groves, switchbacks, and the Tyrrhenian below.",
    cover: { publicId: "Europe/Italy/Almafi/_DSF9255_jzxsfy", alt: "Travel photograph from Amalfi, Italy", city: "Amalfi" },
    photos: [
      { publicId: "Europe/Italy/Almafi/_DSF9255_jzxsfy", alt: "Travel photograph from Amalfi, Italy", city: "Amalfi" },
      { publicId: "Europe/Italy/Almafi/_DSF9295_wyzxee", alt: "Travel photograph from Amalfi, Italy", city: "Amalfi" },
      { publicId: "Europe/Italy/Almafi/_DSF9421_crjgez", alt: "Travel photograph from Amalfi, Italy", city: "Amalfi" },
      { publicId: "Europe/Italy/Almafi/_DSF9504_ll1jxp", alt: "Travel photograph from Amalfi, Italy", city: "Amalfi" },
    ],
  },
  {
    slug: "capri",
    title: "Capri",
    country: "Italy",
    description: "An island that knows it's being photographed.",
    cover: { publicId: "Europe/Italy/Capri/_DSF9090_aal9hc", alt: "Travel photograph from Capri, Italy", city: "Capri" },
    photos: [
      { publicId: "Europe/Italy/Capri/_DSF9090_aal9hc", alt: "Travel photograph from Capri, Italy", city: "Capri" },
      { publicId: "Europe/Italy/Capri/_DSF9096_gff4im", alt: "Travel photograph from Capri, Italy", city: "Capri" },
      { publicId: "Europe/Italy/Capri/_DSF9114_dy0nyf", alt: "Travel photograph from Capri, Italy", city: "Capri" },
      { publicId: "Europe/Italy/Capri/_DSF9118_vuhbjv", alt: "Travel photograph from Capri, Italy", city: "Capri" },
      { publicId: "Europe/Italy/Capri/_DSF9122_k8rzb5", alt: "Travel photograph from Capri, Italy", city: "Capri" },
      { publicId: "Europe/Italy/Capri/_DSF9125_xtf7kp", alt: "Travel photograph from Capri, Italy", city: "Capri" },
      { publicId: "Europe/Italy/Capri/_DSF9126_adu2f0", alt: "Travel photograph from Capri, Italy", city: "Capri" },
      { publicId: "Europe/Italy/Capri/_DSF9132_kzy8ee", alt: "Travel photograph from Capri, Italy", city: "Capri" },
      { publicId: "Europe/Italy/Capri/_DSF9137_nwu1l6", alt: "Travel photograph from Capri, Italy", city: "Capri" },
      { publicId: "Europe/Italy/Capri/_DSF9138_pdr6k5", alt: "Travel photograph from Capri, Italy", city: "Capri" },
      { publicId: "Europe/Italy/Capri/_DSF9144_g9u3ka", alt: "Travel photograph from Capri, Italy", city: "Capri" },
      { publicId: "Europe/Italy/Capri/_DSF9150_joqipy", alt: "Travel photograph from Capri, Italy", city: "Capri" },
      { publicId: "Europe/Italy/Capri/_DSF9362_gtqkv1", alt: "Travel photograph from Capri, Italy", city: "Capri" },
      { publicId: "Europe/Italy/Capri/_DSF9367_opek8v", alt: "Travel photograph from Capri, Italy", city: "Capri" },
      { publicId: "Europe/Italy/Capri/_DSF9369_jju0yy", alt: "Travel photograph from Capri, Italy", city: "Capri" },
    ],
  },
  {
    slug: "sorrento",
    title: "Sorrento",
    country: "Italy",
    description: "Cliff-top views over the Bay of Naples.",
    cover: { publicId: "Europe/Italy/Sorrento/_DSF9191_esjt4s", alt: "Travel photograph from Sorrento, Italy", city: "Sorrento" },
    photos: [
      { publicId: "Europe/Italy/Sorrento/_DSF9191_esjt4s", alt: "Travel photograph from Sorrento, Italy", city: "Sorrento" },
      { publicId: "Europe/Italy/Sorrento/_DSF9222_ngcpux", alt: "Travel photograph from Sorrento, Italy", city: "Sorrento" },
      { publicId: "Europe/Italy/Sorrento/_DSF9237_gk1wgd", alt: "Travel photograph from Sorrento, Italy", city: "Sorrento" },
      { publicId: "Europe/Italy/Sorrento/_DSF9398_fsvv6l", alt: "Travel photograph from Sorrento, Italy", city: "Sorrento" },
      { publicId: "Europe/Italy/Sorrento/_DSF9403_nka6kb", alt: "Travel photograph from Sorrento, Italy", city: "Sorrento" },
    ],
  },
  {
    slug: "napoli",
    title: "Napoli",
    country: "Italy",
    description: "Loud, layered, alive. Napoli doesn't pose.",
    cover: { publicId: "Europe/Italy/Napoli/_DSF9396_s59bys", alt: "Travel photograph from Napoli, Italy", city: "Napoli" },
    photos: [
      { publicId: "Europe/Italy/Napoli/_DSF9396_s59bys", alt: "Travel photograph from Napoli, Italy", city: "Napoli" },
      { publicId: "Europe/Italy/Napoli/_DSF9397_powrxr", alt: "Travel photograph from Napoli, Italy", city: "Napoli" },
      { publicId: "Europe/Italy/Napoli/_DSF9399_rzuh6v", alt: "Travel photograph from Napoli, Italy", city: "Napoli" },
      { publicId: "Europe/Italy/Napoli/_DSF9401_qixppd", alt: "Travel photograph from Napoli, Italy", city: "Napoli" },
      { publicId: "Europe/Italy/Napoli/_DSF9404_ud5sqx", alt: "Travel photograph from Napoli, Italy", city: "Napoli" },
      { publicId: "Europe/Italy/Napoli/_DSF9444_yznq17", alt: "Travel photograph from Napoli, Italy", city: "Napoli" },
      { publicId: "Europe/Italy/Napoli/_DSF9569_tljv2h", alt: "Travel photograph from Napoli, Italy", city: "Napoli" },
      { publicId: "Europe/Italy/Napoli/_DSF9599_xk9smn", alt: "Travel photograph from Napoli, Italy", city: "Napoli" },
      { publicId: "Europe/Italy/Napoli/_DSF9615_nqnxpj", alt: "Travel photograph from Napoli, Italy", city: "Napoli" },
      { publicId: "Europe/Italy/Napoli/_DSF9617_gxoydj", alt: "Travel photograph from Napoli, Italy", city: "Napoli" },
      { publicId: "Europe/Italy/Napoli/_DSF9629_gtzmvg", alt: "Travel photograph from Napoli, Italy", city: "Napoli" },
      { publicId: "Europe/Italy/Napoli/_DSF9651_qognlf", alt: "Travel photograph from Napoli, Italy", city: "Napoli" },
      { publicId: "Europe/Italy/Napoli/_DSF9663_kfqqql", alt: "Travel photograph from Napoli, Italy", city: "Napoli" },
    ],
  },
  {
    slug: "florence",
    title: "Florence",
    country: "Italy",
    description: "Renaissance stone and afternoon light on the Arno.",
    cover: { publicId: "Europe/Italy/Florence/DSCF6620_jib8sh", alt: "Travel photograph from Florence, Italy", city: "Florence" },
    photos: [
      { publicId: "Europe/Italy/Florence/DSCF6620_jib8sh", alt: "Travel photograph from Florence, Italy", city: "Florence" },
      { publicId: "Europe/Italy/Florence/DSCF6639_grvnfp", alt: "Travel photograph from Florence, Italy", city: "Florence" },
      { publicId: "Europe/Italy/Florence/DSCF6669_c2km8b", alt: "Travel photograph from Florence, Italy", city: "Florence" },
      { publicId: "Europe/Italy/Florence/DSCF6825_wcvhwa", alt: "Travel photograph from Florence, Italy", city: "Florence" },
      { publicId: "Europe/Italy/Florence/DSCF6881_plvk7j", alt: "Travel photograph from Florence, Italy", city: "Florence" },
      { publicId: "Europe/Italy/Florence/DSCF8532_aghfou", alt: "Travel photograph from Florence, Italy", city: "Florence" },
      { publicId: "Europe/Italy/Florence/DSCF8562_mtcpds", alt: "Travel photograph from Florence, Italy", city: "Florence" },
      { publicId: "Europe/Italy/Florence/DSCF8613_k3qhul", alt: "Travel photograph from Florence, Italy", city: "Florence" },
      { publicId: "Europe/Italy/Florence/DSCF8751_ft76mj", alt: "Travel photograph from Florence, Italy", city: "Florence" },
    ],
  },
  {
    slug: "matera",
    title: "Matera",
    country: "Italy",
    description: "Cave dwellings and honey-colored stone in Basilicata.",
    cover: { publicId: "Europe/Italy/Matera/_DSF8717_ynbtnm", alt: "Travel photograph from Matera, Italy", city: "Matera" },
    photos: [
      { publicId: "Europe/Italy/Matera/_DSF8717_ynbtnm", alt: "Travel photograph from Matera, Italy", city: "Matera" },
      { publicId: "Europe/Italy/Matera/_DSF8726_ztg3ko", alt: "Travel photograph from Matera, Italy", city: "Matera" },
      { publicId: "Europe/Italy/Matera/_DSF8728_ht2fia", alt: "Travel photograph from Matera, Italy", city: "Matera" },
      { publicId: "Europe/Italy/Matera/_DSF8745_yk1sp3", alt: "Travel photograph from Matera, Italy", city: "Matera" },
      { publicId: "Europe/Italy/Matera/_DSF9200_imaexj", alt: "Travel photograph from Matera, Italy", city: "Matera" },
    ],
  },
  {
    slug: "alberobello",
    title: "Alberobello",
    country: "Italy",
    description: "The trulli town — white cones against a blue Puglia sky.",
    cover: { publicId: "Europe/Italy/Alberobello/_DSF8822_tf80xt", alt: "Travel photograph from Alberobello, Italy", city: "Alberobello" },
    photos: [
      { publicId: "Europe/Italy/Alberobello/_DSF8822_tf80xt", alt: "Travel photograph from Alberobello, Italy", city: "Alberobello" },
      { publicId: "Europe/Italy/Alberobello/_DSF8835_tokawi", alt: "Travel photograph from Alberobello, Italy", city: "Alberobello" },
      { publicId: "Europe/Italy/Alberobello/_DSF9218_kv7hzz", alt: "Travel photograph from Alberobello, Italy", city: "Alberobello" },
      { publicId: "Europe/Italy/Alberobello/_DSF9226_upb7zs", alt: "Travel photograph from Alberobello, Italy", city: "Alberobello" },
      { publicId: "Europe/Italy/Alberobello/_DSF9228_eavak4", alt: "Travel photograph from Alberobello, Italy", city: "Alberobello" },
      { publicId: "Europe/Italy/Alberobello/_DSF9233_reg0vy", alt: "Travel photograph from Alberobello, Italy", city: "Alberobello" },
    ],
  },
  {
    slug: "bari",
    title: "Bari",
    country: "Italy",
    description: "Old-town alleys and Adriatic seafront in Puglia's capital.",
    cover: { publicId: "Europe/Italy/Bari/_DSF8921_tkksf4", alt: "Travel photograph from Bari, Italy", city: "Bari" },
    photos: [
      { publicId: "Europe/Italy/Bari/_DSF8921_tkksf4", alt: "Travel photograph from Bari, Italy", city: "Bari" },
      { publicId: "Europe/Italy/Bari/_DSF8924_omhrlo", alt: "Travel photograph from Bari, Italy", city: "Bari" },
      { publicId: "Europe/Italy/Bari/_DSF8931_bv6dzk", alt: "Travel photograph from Bari, Italy", city: "Bari" },
      { publicId: "Europe/Italy/Bari/_DSF8937_uxmvmu", alt: "Travel photograph from Bari, Italy", city: "Bari" },
      { publicId: "Europe/Italy/Bari/_DSF9248_qpwc3u", alt: "Travel photograph from Bari, Italy", city: "Bari" },
      { publicId: "Europe/Italy/Bari/_DSF9254_owr73m", alt: "Travel photograph from Bari, Italy", city: "Bari" },
      { publicId: "Europe/Italy/Bari/_DSF9265_zfatky", alt: "Travel photograph from Bari, Italy", city: "Bari" },
    ],
  },
  {
    slug: "monopoli",
    title: "Monopoli",
    country: "Italy",
    description: "A working harbor in Puglia, blue boats and white stone.",
    cover: { publicId: "Europe/Italy/Monopoli/_DSF8864_bhsxls", alt: "Travel photograph from Monopoli, Italy", city: "Monopoli" },
    photos: [
      { publicId: "Europe/Italy/Monopoli/_DSF8864_bhsxls", alt: "Travel photograph from Monopoli, Italy", city: "Monopoli" },
      { publicId: "Europe/Italy/Monopoli/_DSF8872_eouaed", alt: "Travel photograph from Monopoli, Italy", city: "Monopoli" },
      { publicId: "Europe/Italy/Monopoli/_DSF8876_n7wqy1", alt: "Travel photograph from Monopoli, Italy", city: "Monopoli" },
      { publicId: "Europe/Italy/Monopoli/_DSF8884_songsu", alt: "Travel photograph from Monopoli, Italy", city: "Monopoli" },
      { publicId: "Europe/Italy/Monopoli/_DSF8916_tumrmv", alt: "Travel photograph from Monopoli, Italy", city: "Monopoli" },
      { publicId: "Europe/Italy/Monopoli/_DSF8918_grrt6v", alt: "Travel photograph from Monopoli, Italy", city: "Monopoli" },
      { publicId: "Europe/Italy/Monopoli/_DSF9241_hlundv", alt: "Travel photograph from Monopoli, Italy", city: "Monopoli" },
      { publicId: "Europe/Italy/Monopoli/_DSF9243_otwi18", alt: "Travel photograph from Monopoli, Italy", city: "Monopoli" },
      { publicId: "Europe/Italy/Monopoli/_DSF9245_i5i9eg", alt: "Travel photograph from Monopoli, Italy", city: "Monopoli" },
      { publicId: "Europe/Italy/Monopoli/_DSF9246_ujjydk", alt: "Travel photograph from Monopoli, Italy", city: "Monopoli" },
    ],
  },
  {
    slug: "pogliano",
    title: "Pogliano",
    country: "Italy",
    description: "Puglia's coastline, shot from the edge.",
    cover: { publicId: "Europe/Italy/Pogliano/_DSF8808_s6ojqt", alt: "Travel photograph from Pogliano, Italy", city: "Pogliano" },
    photos: [
      { publicId: "Europe/Italy/Pogliano/_DSF8808_s6ojqt", alt: "Travel photograph from Pogliano, Italy", city: "Pogliano" },
      { publicId: "Europe/Italy/Pogliano/_DSF8965_zspn3j", alt: "Travel photograph from Pogliano, Italy", city: "Pogliano" },
      { publicId: "Europe/Italy/Pogliano/_DSF8969_wh36tz", alt: "Travel photograph from Pogliano, Italy", city: "Pogliano" },
      { publicId: "Europe/Italy/Pogliano/_DSF8986_tgxsam", alt: "Travel photograph from Pogliano, Italy", city: "Pogliano" },
      { publicId: "Europe/Italy/Pogliano/_DSF8987_e2d6j2", alt: "Travel photograph from Pogliano, Italy", city: "Pogliano" },
      { publicId: "Europe/Italy/Pogliano/_DSF8991_m6pvwq", alt: "Travel photograph from Pogliano, Italy", city: "Pogliano" },
      { publicId: "Europe/Italy/Pogliano/_DSF8992_xhrfnn", alt: "Travel photograph from Pogliano, Italy", city: "Pogliano" },
    ],
  },
  {
    slug: "zurich",
    title: "Zurich",
    country: "Switzerland",
    description: "Clean lines and lake light in Switzerland's largest city.",
    cover: { publicId: "Europe/Switzerland/Zurich/_DSF8236_uzqajv", alt: "Travel photograph from Zurich, Switzerland", city: "Zurich" },
    photos: [
      { publicId: "Europe/Switzerland/Zurich/_DSF8236_uzqajv", alt: "Travel photograph from Zurich, Switzerland", city: "Zurich" },
      { publicId: "Europe/Switzerland/Zurich/_DSF8239_eirykr", alt: "Travel photograph from Zurich, Switzerland", city: "Zurich" },
      { publicId: "Europe/Switzerland/Zurich/_DSF8256_ybsfm0", alt: "Travel photograph from Zurich, Switzerland", city: "Zurich" },
      { publicId: "Europe/Switzerland/Zurich/_DSF8268_xxecvv", alt: "Travel photograph from Zurich, Switzerland", city: "Zurich" },
      { publicId: "Europe/Switzerland/Zurich/_DSF8758_nk1zcu", alt: "Travel photograph from Zurich, Switzerland", city: "Zurich" },
      { publicId: "Europe/Switzerland/Zurich/_DSF8763_azqtfw", alt: "Travel photograph from Zurich, Switzerland", city: "Zurich" },
      { publicId: "Europe/Switzerland/Zurich/_DSF8766_phpnyb", alt: "Travel photograph from Zurich, Switzerland", city: "Zurich" },
    ],
  },
  {
    slug: "lugano",
    title: "Lugano",
    country: "Switzerland",
    description: "Where Switzerland speaks Italian — palm trees against alpine water.",
    cover: { publicId: "Europe/Switzerland/Lugano/_DSF8312_snfpb1", alt: "Travel photograph from Lugano, Switzerland", city: "Lugano" },
    photos: [
      { publicId: "Europe/Switzerland/Lugano/_DSF8312_snfpb1", alt: "Travel photograph from Lugano, Switzerland", city: "Lugano" },
      { publicId: "Europe/Switzerland/Lugano/_DSF8319_jxyqd0", alt: "Travel photograph from Lugano, Switzerland", city: "Lugano" },
      { publicId: "Europe/Switzerland/Lugano/_DSF8328_zsaiwb", alt: "Travel photograph from Lugano, Switzerland", city: "Lugano" },
      { publicId: "Europe/Switzerland/Lugano/_DSF8334_na3bn3", alt: "Travel photograph from Lugano, Switzerland", city: "Lugano" },
      { publicId: "Europe/Switzerland/Lugano/_DSF8393_o9kp9h", alt: "Travel photograph from Lugano, Switzerland", city: "Lugano" },
    ],
  },
  {
    slug: "vienna",
    title: "Vienna",
    country: "Austria",
    description: "Imperial facades and café light. Vienna in passing.",
    cover: { publicId: "Europe/Austria/Vienna/cpjimzod3oabekff39ru", alt: "Travel photograph from Vienna, Austria", city: "Vienna" },
    photos: [
      { publicId: "Europe/Austria/Vienna/cpjimzod3oabekff39ru", alt: "Travel photograph from Vienna, Austria", city: "Vienna" },
      { publicId: "Europe/Austria/Vienna/kr7biwghwnrmi6s50wus", alt: "Travel photograph from Vienna, Austria", city: "Vienna" },
      { publicId: "Europe/Austria/Vienna/lakdvru1s6uqwugb0huf", alt: "Travel photograph from Vienna, Austria", city: "Vienna" },
      { publicId: "Europe/Austria/Vienna/q2urfajnlovnggz2rjgx", alt: "Travel photograph from Vienna, Austria", city: "Vienna" },
      { publicId: "Europe/Austria/Vienna/uszawu6xn7aishutq1dx", alt: "Travel photograph from Vienna, Austria", city: "Vienna" },
      { publicId: "Europe/Austria/Vienna/we18qdnfbdcfbbvsnqv1", alt: "Travel photograph from Vienna, Austria", city: "Vienna" },
      { publicId: "Europe/Austria/Vienna/wuozgshr1wfl6fteoizm", alt: "Travel photograph from Vienna, Austria", city: "Vienna" },
    ],
  },
  {
    slug: "salzburg",
    title: "Salzburg",
    country: "Austria",
    description: "Baroque streets and alpine light in Salzburg's old town.",
    cover: { publicId: "Europe/Austria/Salzburg/cwftoddlgrpkpcokd6ae", alt: "Travel photograph from Salzburg, Austria", city: "Salzburg" },
    photos: [
      { publicId: "Europe/Austria/Salzburg/cwftoddlgrpkpcokd6ae", alt: "Travel photograph from Salzburg, Austria", city: "Salzburg" },
      { publicId: "Europe/Austria/Salzburg/fup4vrfjn9flgk2fssqy", alt: "Travel photograph from Salzburg, Austria", city: "Salzburg" },
      { publicId: "Europe/Austria/Salzburg/idnpfspiqqdjut5bjsr3", alt: "Travel photograph from Salzburg, Austria", city: "Salzburg" },
      { publicId: "Europe/Austria/Salzburg/k3ul8sn0edcx9oofed2d", alt: "Travel photograph from Salzburg, Austria", city: "Salzburg" },
      { publicId: "Europe/Austria/Salzburg/mjsuroc19gre40sazzpm", alt: "Travel photograph from Salzburg, Austria", city: "Salzburg" },
      { publicId: "Europe/Austria/Salzburg/osx0nkkit1m3lq4dmeki", alt: "Travel photograph from Salzburg, Austria", city: "Salzburg" },
      { publicId: "Europe/Austria/Salzburg/s5mt7ldzeeoxtsp9l7bk", alt: "Travel photograph from Salzburg, Austria", city: "Salzburg" },
      { publicId: "Europe/Austria/Salzburg/s7gj7gkihfpfpbfzbwe7", alt: "Travel photograph from Salzburg, Austria", city: "Salzburg" },
      { publicId: "Europe/Austria/Salzburg/usyjkngvadgtll45vbyd", alt: "Travel photograph from Salzburg, Austria", city: "Salzburg" },
      { publicId: "Europe/Austria/Salzburg/z5xqd2maligmnbef9brw", alt: "Travel photograph from Salzburg, Austria", city: "Salzburg" },
    ],
  },
  {
    slug: "innsbruck",
    title: "Innsbruck",
    country: "Austria",
    description: "A city with mountains at the end of every street.",
    cover: { publicId: "Europe/Austria/Innsbruck/br5exgsyswn9vrktrxss", alt: "Travel photograph from Innsbruck, Austria", city: "Innsbruck" },
    photos: [
      { publicId: "Europe/Austria/Innsbruck/br5exgsyswn9vrktrxss", alt: "Travel photograph from Innsbruck, Austria", city: "Innsbruck" },
      { publicId: "Europe/Austria/Innsbruck/gosr2qly03eyuhlc2kca", alt: "Travel photograph from Innsbruck, Austria", city: "Innsbruck" },
      { publicId: "Europe/Austria/Innsbruck/gsxk25hm5zeqnlzdojr4", alt: "Travel photograph from Innsbruck, Austria", city: "Innsbruck" },
      { publicId: "Europe/Austria/Innsbruck/k278zw454xnskjvrbxod", alt: "Travel photograph from Innsbruck, Austria", city: "Innsbruck" },
      { publicId: "Europe/Austria/Innsbruck/lymzxyd3zvlganso1ea6", alt: "Travel photograph from Innsbruck, Austria", city: "Innsbruck" },
      { publicId: "Europe/Austria/Innsbruck/ms3mdgmmlkdizuwmbemd", alt: "Travel photograph from Innsbruck, Austria", city: "Innsbruck" },
      { publicId: "Europe/Austria/Innsbruck/n4gf4pvx3mqls3s6cles", alt: "Travel photograph from Innsbruck, Austria", city: "Innsbruck" },
      { publicId: "Europe/Austria/Innsbruck/tjlskiwqfvzfkgvtukvk", alt: "Travel photograph from Innsbruck, Austria", city: "Innsbruck" },
      { publicId: "Europe/Austria/Innsbruck/u46pvumaqvrhyh8zkbwa", alt: "Travel photograph from Innsbruck, Austria", city: "Innsbruck" },
    ],
  },
  {
    slug: "liechtenstein",
    title: "Liechtenstein",
    country: "Liechtenstein",
    description: "A country you can walk across, framed by the Alps.",
    cover: { publicId: "Europe/Liechtenstein/_DSF8168_vrpnye", alt: "Travel photograph from Liechtenstein, Liechtenstein", city: "Liechtenstein" },
    photos: [
      { publicId: "Europe/Liechtenstein/_DSF8168_vrpnye", alt: "Travel photograph from Liechtenstein, Liechtenstein", city: "Liechtenstein" },
      { publicId: "Europe/Liechtenstein/_DSF8170_thp6tt", alt: "Travel photograph from Liechtenstein, Liechtenstein", city: "Liechtenstein" },
      { publicId: "Europe/Liechtenstein/_DSF8180_fzdwqi", alt: "Travel photograph from Liechtenstein, Liechtenstein", city: "Liechtenstein" },
      { publicId: "Europe/Liechtenstein/_DSF8185_tlduzn", alt: "Travel photograph from Liechtenstein, Liechtenstein", city: "Liechtenstein" },
      { publicId: "Europe/Liechtenstein/_DSF8193_evw25b", alt: "Travel photograph from Liechtenstein, Liechtenstein", city: "Liechtenstein" },
      { publicId: "Europe/Liechtenstein/_DSF8723_uwjtob", alt: "Travel photograph from Liechtenstein, Liechtenstein", city: "Liechtenstein" },
    ],
  },
  {
    slug: "brugge",
    title: "Brugge",
    country: "Belgium",
    description: "Canals, gables, and a town that never left the Middle Ages.",
    cover: { publicId: "Europe/Belgium/Brugge/DSCF4578_px30cg", alt: "Travel photograph from Brugge, Belgium", city: "Brugge" },
    photos: [
      { publicId: "Europe/Belgium/Brugge/DSCF4578_px30cg", alt: "Travel photograph from Brugge, Belgium", city: "Brugge" },
      { publicId: "Europe/Belgium/Brugge/DSCF4756_vxptpv", alt: "Travel photograph from Brugge, Belgium", city: "Brugge" },
      { publicId: "Europe/Belgium/Brugge/DSCF4757_zuevxh", alt: "Travel photograph from Brugge, Belgium", city: "Brugge" },
      { publicId: "Europe/Belgium/Brugge/_DSF4827_v15dvn", alt: "Travel photograph from Brugge, Belgium", city: "Brugge" },
    ],
  },
  {
    slug: "brussels",
    title: "Brussels",
    country: "Belgium",
    description: "Grand squares and grey skies in the Belgian capital.",
    cover: { publicId: "Europe/Belgium/Brussels/DSCF4182_ybyggu", alt: "Travel photograph from Brussels, Belgium", city: "Brussels" },
    photos: [
      { publicId: "Europe/Belgium/Brussels/DSCF4182_ybyggu", alt: "Travel photograph from Brussels, Belgium", city: "Brussels" },
      { publicId: "Europe/Belgium/Brussels/DSCF4195_u1dswq", alt: "Travel photograph from Brussels, Belgium", city: "Brussels" },
      { publicId: "Europe/Belgium/Brussels/DSCF4198_bwxz9s", alt: "Travel photograph from Brussels, Belgium", city: "Brussels" },
      { publicId: "Europe/Belgium/Brussels/DSCF4244_lclepv", alt: "Travel photograph from Brussels, Belgium", city: "Brussels" },
      { publicId: "Europe/Belgium/Brussels/DSCF4502_dhisiy", alt: "Travel photograph from Brussels, Belgium", city: "Brussels" },
      { publicId: "Europe/Belgium/Brussels/_DSF4443_pdfgo4", alt: "Travel photograph from Brussels, Belgium", city: "Brussels" },
    ],
  },
  {
    slug: "porto",
    title: "Porto",
    country: "Portugal",
    description: "Tiled facades stacked over the Douro.",
    cover: { publicId: "Europe/Portugal/Porto/DSCF5554_tbzpon", alt: "Travel photograph from Porto, Portugal", city: "Porto" },
    photos: [
      { publicId: "Europe/Portugal/Porto/DSCF5334_fkwkyt", alt: "Travel photograph from Porto, Portugal", city: "Porto" },
      { publicId: "Europe/Portugal/Porto/DSCF5345_fvtogz", alt: "Travel photograph from Porto, Portugal", city: "Porto" },
      { publicId: "Europe/Portugal/Porto/DSCF5352_c1rda2", alt: "Travel photograph from Porto, Portugal", city: "Porto" },
      { publicId: "Europe/Portugal/Porto/DSCF5459_v1pkhh", alt: "Travel photograph from Porto, Portugal", city: "Porto" },
      { publicId: "Europe/Portugal/Porto/DSCF5477_afopmz", alt: "Travel photograph from Porto, Portugal", city: "Porto" },
      { publicId: "Europe/Portugal/Porto/DSCF5512_tetkcb", alt: "Travel photograph from Porto, Portugal", city: "Porto" },
      { publicId: "Europe/Portugal/Porto/DSCF5554_tbzpon", alt: "Travel photograph from Porto, Portugal", city: "Porto" },
      { publicId: "Europe/Portugal/Porto/_DSF5660_monjnl", alt: "Travel photograph from Porto, Portugal", city: "Porto" },
      { publicId: "Europe/Portugal/Porto/_DSF5678_kihfy4", alt: "Travel photograph from Porto, Portugal", city: "Porto" },
      { publicId: "Europe/Portugal/Porto/_DSF5681_mt5stf", alt: "Travel photograph from Porto, Portugal", city: "Porto" },
      { publicId: "Europe/Portugal/Porto/_DSF5682_auepvd", alt: "Travel photograph from Porto, Portugal", city: "Porto" },
      { publicId: "Europe/Portugal/Porto/_DSF5704_synspf", alt: "Travel photograph from Porto, Portugal", city: "Porto" },
      { publicId: "Europe/Portugal/Porto/_DSF5714_vfjem6", alt: "Travel photograph from Porto, Portugal", city: "Porto" },
      { publicId: "Europe/Portugal/Porto/_DSF5721_hfruqh", alt: "Travel photograph from Porto, Portugal", city: "Porto" },
      { publicId: "Europe/Portugal/Porto/_DSF5723_xoas3d", alt: "Travel photograph from Porto, Portugal", city: "Porto" },
      { publicId: "Europe/Portugal/Porto/_DSF5733_gva9wf", alt: "Travel photograph from Porto, Portugal", city: "Porto" },
    ],
  },
  {
    slug: "braga",
    title: "Braga",
    country: "Portugal",
    description: "Tiles, churches, and slow afternoons in Portugal's oldest city.",
    cover: { publicId: "Europe/Portugal/Braga/DSCF5590_onvagd", alt: "Travel photograph from Braga, Portugal", city: "Braga" },
    photos: [
      { publicId: "Europe/Portugal/Braga/DSCF5590_onvagd", alt: "Travel photograph from Braga, Portugal", city: "Braga" },
      { publicId: "Europe/Portugal/Braga/_DSF5631_thcn3s", alt: "Travel photograph from Braga, Portugal", city: "Braga" },
      { publicId: "Europe/Portugal/Braga/_DSF5800_ff7vij", alt: "Travel photograph from Braga, Portugal", city: "Braga" },
      { publicId: "Europe/Portugal/Braga/_DSF5808_e0uozy", alt: "Travel photograph from Braga, Portugal", city: "Braga" },
      { publicId: "Europe/Portugal/Braga/_DSF5815_rmofdi", alt: "Travel photograph from Braga, Portugal", city: "Braga" },
      { publicId: "Europe/Portugal/Braga/_DSF5843_fjmaju", alt: "Travel photograph from Braga, Portugal", city: "Braga" },
      { publicId: "Europe/Portugal/Braga/_DSF5846_g9rdnx", alt: "Travel photograph from Braga, Portugal", city: "Braga" },
    ],
  },
  {
    slug: "tulum",
    title: "Tulum",
    country: "Mexico",
    description: "Jungle, ruins, and the Caribbean in Yucatán light.",
    cover: { publicId: "North America/Mexico/Tulum/_DSF9665_iqutbn", alt: "Travel photograph from Tulum, Mexico", city: "Tulum" },
    photos: [
      { publicId: "North America/Mexico/Tulum/_DSF9665_iqutbn", alt: "Travel photograph from Tulum, Mexico", city: "Tulum" },
      { publicId: "North America/Mexico/Tulum/_DSF9667_zfer8e", alt: "Travel photograph from Tulum, Mexico", city: "Tulum" },
      { publicId: "North America/Mexico/Tulum/_DSF9694_ktjwrj", alt: "Travel photograph from Tulum, Mexico", city: "Tulum" },
      { publicId: "North America/Mexico/Tulum/_DSF9696_yoht6y", alt: "Travel photograph from Tulum, Mexico", city: "Tulum" },
      { publicId: "North America/Mexico/Tulum/_DSF9724_zxb2so", alt: "Travel photograph from Tulum, Mexico", city: "Tulum" },
      { publicId: "North America/Mexico/Tulum/_DSF9741_w20ddi", alt: "Travel photograph from Tulum, Mexico", city: "Tulum" },
      { publicId: "North America/Mexico/Tulum/_DSF9745_hueebj", alt: "Travel photograph from Tulum, Mexico", city: "Tulum" },
      { publicId: "North America/Mexico/Tulum/_DSF9831_jda4rw", alt: "Travel photograph from Tulum, Mexico", city: "Tulum" },
      { publicId: "North America/Mexico/Tulum/_DSF9850_ty0aip", alt: "Travel photograph from Tulum, Mexico", city: "Tulum" },
      { publicId: "North America/Mexico/Tulum/_DSF9851_jyv668", alt: "Travel photograph from Tulum, Mexico", city: "Tulum" },
      { publicId: "North America/Mexico/Tulum/_DSF9857_joixol", alt: "Travel photograph from Tulum, Mexico", city: "Tulum" },
    ],
  },
  {
    slug: "punta-cana",
    title: "Punta Cana",
    country: "Dominican Republic",
    description: "Palms and Atlantic turquoise on the Dominican coast.",
    cover: { publicId: "Central America/Punta Cana/_X101133_hml3ob", alt: "Travel photograph from Punta Cana, Dominican Republic", city: "Punta Cana" },
    photos: [
      { publicId: "Central America/Punta Cana/_X100872_ypyv0g", alt: "Travel photograph from Punta Cana, Dominican Republic", city: "Punta Cana" },
      { publicId: "Central America/Punta Cana/_X100909_rjod83", alt: "Travel photograph from Punta Cana, Dominican Republic", city: "Punta Cana" },
      { publicId: "Central America/Punta Cana/_X100910_mvyvva", alt: "Travel photograph from Punta Cana, Dominican Republic", city: "Punta Cana" },
      { publicId: "Central America/Punta Cana/_X101027_qgavqr", alt: "Travel photograph from Punta Cana, Dominican Republic", city: "Punta Cana" },
      { publicId: "Central America/Punta Cana/_X101058_d8jqmt", alt: "Travel photograph from Punta Cana, Dominican Republic", city: "Punta Cana" },
      { publicId: "Central America/Punta Cana/_X101083_m7pnjo", alt: "Travel photograph from Punta Cana, Dominican Republic", city: "Punta Cana" },
      { publicId: "Central America/Punta Cana/_X101092_aet0yf", alt: "Travel photograph from Punta Cana, Dominican Republic", city: "Punta Cana" },
      { publicId: "Central America/Punta Cana/_X101102_yyjktt", alt: "Travel photograph from Punta Cana, Dominican Republic", city: "Punta Cana" },
      { publicId: "Central America/Punta Cana/_X101130-Edit_f2whpk", alt: "Travel photograph from Punta Cana, Dominican Republic", city: "Punta Cana" },
      { publicId: "Central America/Punta Cana/_X101133_hml3ob", alt: "Travel photograph from Punta Cana, Dominican Republic", city: "Punta Cana" },
      { publicId: "Central America/Punta Cana/_X101175_qajori", alt: "Travel photograph from Punta Cana, Dominican Republic", city: "Punta Cana" },
      { publicId: "Central America/Punta Cana/_XPR1892_zyu9gg", alt: "Travel photograph from Punta Cana, Dominican Republic", city: "Punta Cana" },
      { publicId: "Central America/Punta Cana/_XPR1894_bshhzw", alt: "Travel photograph from Punta Cana, Dominican Republic", city: "Punta Cana" },
      { publicId: "Central America/Punta Cana/_XPR1901_zbkav0", alt: "Travel photograph from Punta Cana, Dominican Republic", city: "Punta Cana" },
    ],
  },
  {
    slug: "inhotim",
    title: "Inhotim",
    country: "Brazil",
    description: "Art in a botanical garden — Inhotim, Minas Gerais.",
    cover: { publicId: "South America/Brasil/Inhotim/_XPR0474_yopejy", alt: "Travel photograph from Inhotim, Brazil", city: "Inhotim" },
    photos: [
      { publicId: "South America/Brasil/Inhotim/_XPR0474_yopejy", alt: "Travel photograph from Inhotim, Brazil", city: "Inhotim" },
      { publicId: "South America/Brasil/Inhotim/_XPR0480_eigzes", alt: "Travel photograph from Inhotim, Brazil", city: "Inhotim" },
      { publicId: "South America/Brasil/Inhotim/_XPR0483_ukrxn0", alt: "Travel photograph from Inhotim, Brazil", city: "Inhotim" },
      { publicId: "South America/Brasil/Inhotim/_XPR0620_erd7a8", alt: "Travel photograph from Inhotim, Brazil", city: "Inhotim" },
      { publicId: "South America/Brasil/Inhotim/_XPR0626_tyi2ze", alt: "Travel photograph from Inhotim, Brazil", city: "Inhotim" },
      { publicId: "South America/Brasil/Inhotim/_XPR0654_an25ls", alt: "Travel photograph from Inhotim, Brazil", city: "Inhotim" },
      { publicId: "South America/Brasil/Inhotim/_XPR0660_gvrbdw", alt: "Travel photograph from Inhotim, Brazil", city: "Inhotim" },
      { publicId: "South America/Brasil/Inhotim/_XPR0682_dpa65q", alt: "Travel photograph from Inhotim, Brazil", city: "Inhotim" },
      { publicId: "South America/Brasil/Inhotim/_XPR0720_xcwieq", alt: "Travel photograph from Inhotim, Brazil", city: "Inhotim" },
      { publicId: "South America/Brasil/Inhotim/_XPR0724_rhrjsm", alt: "Travel photograph from Inhotim, Brazil", city: "Inhotim" },
    ],
  },
  {
    slug: "brasilia",
    title: "Brasília",
    country: "Brazil",
    description: "Niemeyer's curves and the capital's planned horizons.",
    cover: { publicId: "South America/Brasil/Brasilia/_DSF7725_vt67kt", alt: "Travel photograph from Brasília, Brazil", city: "Brasília" },
    photos: [
      { publicId: "South America/Brasil/Brasilia/_DSF7725_vt67kt", alt: "Travel photograph from Brasília, Brazil", city: "Brasília" },
      { publicId: "South America/Brasil/Brasilia/_DSF7726_oncagd", alt: "Travel photograph from Brasília, Brazil", city: "Brasília" },
      { publicId: "South America/Brasil/Brasilia/_DSF7770_ivaned", alt: "Travel photograph from Brasília, Brazil", city: "Brasília" },
      { publicId: "South America/Brasil/Brasilia/_DSF7774_f8o9nu", alt: "Travel photograph from Brasília, Brazil", city: "Brasília" },
    ],
  },
  {
    slug: "montevideo",
    title: "Montevideo",
    country: "Uruguay",
    description: "The Rambla, the old town, and the Río de la Plata.",
    cover: { publicId: "South America/Uruguay/Montevideo/_DSF0015_w2x8ku", alt: "Travel photograph from Montevideo, Uruguay", city: "Montevideo" },
    photos: [
      { publicId: "South America/Uruguay/Montevideo/_DSF0015_w2x8ku", alt: "Travel photograph from Montevideo, Uruguay", city: "Montevideo" },
      { publicId: "South America/Uruguay/Montevideo/_DSF0076_fe1wkn", alt: "Travel photograph from Montevideo, Uruguay", city: "Montevideo" },
      { publicId: "South America/Uruguay/Montevideo/_XPR0205_bp7o55", alt: "Travel photograph from Montevideo, Uruguay", city: "Montevideo" },
    ],
  },
];

export const getAlbum = (slug: string): Album | undefined =>
  albums.find((album) => album.slug === slug);

/** All albums have real photos now; kept for API compatibility. */
export const realAlbums = albums.filter((album) => !album.placeholderImages);
